name: Deploy to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload-api-artifacts:
    uses: plxtra/motif/.github/workflows/upload-api-artifacts.yml@main
    secrets:
      MOTIF_UPLOAD_API_ARTIFACTS_ACCESS: ${{ secrets.MOTIF_UPLOAD_API_ARTIFACTS_ACCESS }}

  build:
    runs-on: ubuntu-latest
    needs: [upload-api-artifacts]
    defaults:
        run:
          working-directory: motif-api # Set working directory to checkout path
    steps:
      - name: Checkout Motif API repository
        uses: actions/checkout@v4
        with:
          path: motif-api # Place in motif-api sub-directory so that docs-build can access ../motif/lib

      - name: Install dependencies
        run: npm ci

      - name: Download lib
        uses: actions/download-artifact@v4
        with:
          name: lib-output
          path: motif/motif/lib # Not relative to working-directory

      - name: Download ts-demo extension
        uses: actions/download-artifact@v4
        with:
          name: ts-demo-extension
          path: motif/extensions/ts-demo

      - name: Download highcharts extension
        uses: actions/download-artifact@v4
        with:
          name: highcharts-extension
          path: motif/extensions/highcharts

      - name: Download website-embed extension
        uses: actions/download-artifact@v4
        with:
          name: website-embed-extension
          path: motif/extensions/website-embed

      - name: Download XOSP config
        uses: actions/download-artifact@v4
        with:
          name: config-xosp-dev
          path: motif/motif/src/config/config.xosp-dev.json

      - name: Build docs
        run: npm run docs:build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: motif-api-docs
          path: motif-api/docs/motif-api  # Not relative to working-directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: motif-api-docs
