name: Deploy to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload-api-artifacts:
    uses: plxtra/motif/.github/workflows/upload-api-artifacts.yml@main
    secrets:
      MOTIF_UPLOAD_API_ARTIFACTS_ACCESS: ${{ secrets.MOTIF_UPLOAD_API_ARTIFACTS_ACCESS }}

  build:
    runs-on: ubuntu-latest
    needs: [upload-api-artifacts]
    defaults:
        run:
          shell: pwsh # Use PowerShell shell for commands
          working-directory: motif-api # Set working directory to checkout path
    steps:
      - name: Checkout Motif API repository
        uses: actions/checkout@v4
        with:
          path: motif-api # Place in motif-api sub-directory so that docs-build can access files from sibling repositories

      - name: Install dependencies
        run: npm ci

      # Get Motif extensions used as examples or guides. No need to install dependencies as dist files not needed.
      - name: Checkout TsDemo Motif extension repository
        uses: actions/checkout@v4
        with:
          repository: plxtra/ts-demo-motif-extension
          path: ts-demo-motif-extension # Not relative to working-directory

      - name: Checkout WebsiteEmbed Motif extension repository
        uses: actions/checkout@v4
        with:
          repository: plxtra/website-embed-motif-extension
          path: website-embed-motif-extension

      - name: Checkout Highcharts Motif extension repository
        uses: actions/checkout@v4
        with:
          repository: plxtra/highcharts-motif-extension
          path: highcharts-motif-extension

      # Get XOSP Motif Config as examples or guides. Nothing to install.
      - name: Checkout XOSP Motif Config repository
        uses: actions/checkout@v4
        with:
          repository: plxtra/xosp-motif-config
          path: xosp-motif-config

      # Get Motif Lib artifact
      - name: Download lib
        uses: actions/download-artifact@v4
        with:
          name: lib-output
          path: motif/lib # Not relative to working-directory

      - name: Build docs
        run: npm run docs:build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: motif-api-docs
          path: motif-api/docs/motif-api  # Not relative to working-directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: motif-api-docs
